project_id = "tzcstwlnflhiqzkmouqd"

[functions.ai-chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.generate-agent-configs]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.generate-activation-message]
verify_jwt = false

[functions.send-activation]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false
