project_id = "tzcstwlnflhiqzkmouqd"

[functions.ai-chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false
